name: Build docker image
on:
  push:
    branches:
      - main
    tags:
      - '**'
    workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.setup.outputs.platforms }}
      tag: ${{ steps.setup.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Matrix
        id: setup
        uses: ./.github/actions/prepare
  deploy:
    needs:
      - prepare
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include: ${{fromJson(needs.prepare.outputs.platforms)}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          platform: ${{ matrix.platform }}
          tag: ${{ needs.prepare.outputs.tag }}
          DOCKER_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKERHUB_TOKEN }}"
  manifest:
    needs:
      - prepare
      - deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/manifest
        with:
          tag: zond-genesis-generator-${{ needs.prepare.outputs.tag }}
          repository: qrledger/qrysm
          platforms: ${{ needs.prepare.outputs.platforms }}
          DOCKER_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKERHUB_TOKEN }}"
